<h2>任务2.3 Numpy进行统计分析
<h3>2.3.1 读/写文件

In [13]:
!mkdir tmp

In [14]:
import numpy as np # 导入numpy库

arr = np.arange(100).reshape(10,10) # 创建一个（10，10）的数组
np.save("./tmp/save_arr",arr) # 保存数组s
print('保存的数组位：\n',arr)

保存的数组位：
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [16]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.arange(0,1.0,0.1)

np.savez("./tmp/save_arr1",arr1,arr2)
print('保存的数组1为：',arr1)
print('保存的数组2为',arr2)

保存的数组1为： [[1 2 3]
 [4 5 6]]
保存的数组2为 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [25]:
loaded_data = np.load("./tmp/save_arr.npy")
print(loaded_data)
loaded_data1= np.load("./tmp/save_arr1.npz")
print(loaded_data1['arr_0'])
print(loaded_data1['arr_1'])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [27]:
arr = np.arange(0,12,0.5).reshape(4,-1)
print(arr)

[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


In [30]:
np.savetxt('./tmp/arr.txt',arr,fmt='%d',delimiter=',')
loaded_data = np.loadtxt('./tmp/arr.txt',delimiter=',')
print(loaded_data)


[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


In [31]:
loaded_date = np.genfromtxt('./tmp/arr.txt',delimiter=',')
print(loaded_data)

[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


In [32]:
loaded_data.dtype

dtype('float64')