<h2>2.2.2  掌握ufunc函数</h2>
<h3>1.常用的ufunc函数运算</h3>

<p>注：数组的形状必须相同</p>

In [1]:
# 引入numpy 包
import numpy as np

# 创建x、y两个数组
x = np.array([1,2,3])
y = np.array([4,5,6])
print('x:',x,'\ny:',y)

x: [1 2 3] 
y: [4 5 6]


数组的四则运算

In [2]:
print(x + y) # 数组相加
print(x - y) # 数组相减
print(x * y) # 数组相乘
print(x / y) # 数组相除
print(x ** y) # 数组幂运算

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


数组的比较运算

In [3]:
x = np.array([1,3,5])
y = np.array([2,3,4])

In [4]:
print(x < y)

[ True False False]


In [5]:
print(x > y)

[False False  True]


In [6]:
print(x == y)

[False  True False]


In [7]:
print(x >= y)

[False  True  True]


In [8]:
print(x <= y)

[ True  True False]


In [9]:
print(x != y)

[ True False  True]


np.all 函数表示逻辑 and ； np.any 函数表示逻辑 or

In [10]:
print(np.all(x == y))

False


In [13]:
print(np.any(x == y))

True


<h3>2.ufunc函数的广播机制</h3>