2.2.1 矩阵运算 加减乘 以及 矩阵特有属性

In [1]:
import numpy as np

matr1 = np.mat("1 2 3;4 5 6;7 8 9")
print(matr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
matr2 = matr1 * 3
print(matr2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [3]:
# 矩阵相加 
print(matr2+matr1)

[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [4]:
# 矩阵相减
print(matr2 - matr1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
# 矩阵相乘
print(matr2 * matr1)

[[ 90 108 126]
 [198 243 288]
 [306 378 450]]


In [6]:
# 对应元素相乘 
# 使用 multiply
print(np.multiply(matr1,matr2))

[[  3  12  27]
 [ 48  75 108]
 [147 192 243]]


In [7]:
# 矩阵转置 T 
print(matr1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
# 矩阵共轭转置 H
print(matr1.H)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
# 矩阵的逆矩阵
arr1 = np.mat("2 0;0 2")
print(arr1)
print(arr1.I)

[[2 0]
 [0 2]]
[[0.5 0. ]
 [0.  0.5]]


In [13]:
# 二维数组的视图
print(matr1.A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
